name: Daily Calendar events to Tasks

on:
  schedule:
    - cron: '0 4 * * *' #Personal preference
  workflow_dispatch: #So it can be manually tested on GitHub

env:
  CREDENTIAL_TOKEN: ${{ secrets.CREDENTIAL_TOKEN }}
  CALENDAR_ID: ${{ secrets.CALENDAR_ID }}

jobs:
  run-daily:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Python setup
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Runs script
        run: |
          python ./src/main.py


